apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: send-to-chat-tg
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Messaging
    tekton.dev/tags: messaging
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le"
spec:
  params:
  - name: bot-token
    type: string
    description: token of the tg bot 
  - name: chat-id
    type: string
    description: group id 
  - name: message
    type: string
    description: plain text message
  steps:
  - name: post
    image: docker.io/curlimages/curl:7.70.0@sha256:031df77a11e5edded840bc761a845eab6e3c2edee22669fb8ad6d59484b6a1c4 #tag: 7.70.0
    script: |
      #!/bin/sh
      /usr/bin/curl -X POST -H 'Content-type: application/json' --data '{"chat_id":"$(params.chat-id)", "text":"$(params.message)"}' https://api.telegram.org/bot$TOKEN/sendMessage
    env:
    - name: TOKEN
      valueFrom:
        secretKeyRef:
          name: $(params.bot-token)
          key: token