apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: build-deploy-template
  namespace: tekton-pipelines
spec:
  params:
  - name: buildRevision
    description: The Git commit revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: build-deploy-
      namespace: tekton-pipelines
    spec:
      serviceAccountName: pipeline
      params:
      - name: buildRevision
        value: $(tt.params.buildRevision)
      - name: appGitUrl
        value: 'git@github.com:simonlaw0711/docker-reactjs.git'
      - name: configGitUrl
        value: 'git@github.com:simonlaw0711/docker-reactjs.git'
      - name: appImage
        value: 'gcr.io/dev-playground-366808/my-app'
      workspaces:
      - name: app-source
        emptyDir: {}
      - name: config-source
        emptyDir: {}
      pipelineRef:
        name: build-deploy
      resources:
        - name: source-repo
          resourceSpec:
            type: git
            params:
            - name: revision
              value: master
            - name: url
              value: git@github.com:simonlaw0711/docker-reactjs.git
        - name: image-source
          resourceSpec:
            type: image
            params:
              - name: url
                value: gcr.io/dev-playground-366808/my-app:$(tt.params.buildRevision)
---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: build-deploy-binding
  namespace: tekton-pipelines
spec:
  params:
  - name: buildRevision
    value: $(body.head_commit.id)
---
